var tree = [["Reflectors","Reflectors.html","",
                [["AbstractReflectionValue","Reflectors\/AbstractReflectionValue.html","",
                [        ]],["ReflectionArray","Reflectors\/ReflectionArray.html"," < AbstractReflectionValue",
                [        ]],["ReflectionBacktrace","Reflectors\/ReflectionBacktrace.html","",
                [        ]],["ReflectionBoolean","Reflectors\/ReflectionBoolean.html"," < AbstractReflectionValue",
                [        ]],["ReflectionFloat","Reflectors\/ReflectionFloat.html"," < AbstractReflectionValue",
                [        ]],["ReflectionInteger","Reflectors\/ReflectionInteger.html"," < AbstractReflectionValue",
                [        ]],["ReflectionParameterValue","Reflectors\/ReflectionParameterValue.html"," < ReflectionParameter",
                [        ]],["ReflectionResource","Reflectors\/ReflectionResource.html"," < AbstractReflectionValue",
                [        ]],["ReflectionSource","Reflectors\/ReflectionSource.html","",
                [        ]],["ReflectionString","Reflectors\/ReflectionString.html"," < AbstractReflectionValue",
                [        ]],["ReflectionTrace","Reflectors\/ReflectionTrace.html","",
                [        ]],["ReflectionValueNull","Reflectors\/ReflectionValueNull.html"," < AbstractReflectionValue",
                [        ]],["ReflectionValueUnknown","Reflectors\/ReflectionValueUnknown.html"," < AbstractReflectionValue",
                [        ]],["ReflectionVariable","Reflectors\/ReflectionVariable.html","",
                [        ]],["ReflectionVariableInterface","Reflectors\/ReflectionVariableInterface.html","",
                [        ]],["ReflectorTrait","Reflectors\/ReflectorTrait.html","",
                [        ]]        ]]        ]

